### ISSUE TITLE
Error while setting a test project up

### ISSUE THREAD

**Issue by dingo-d** [infinum/js-cra-starter#1]
I'm testing this out a bit and first I got an error due to npm naming restrictions, so I put the project name in lowercase letters and I got this error

```sh
> npx @infinumjs/cra-starter -s rafflebot
npx: installed 8 in 2.522s
[███████-------------] 4/11: Moving base files around{ [Error: ENOENT: no such file or directory, rename '/Users/infinum-denis/rafflebot/src/App.test.tsx' -> '/Users/infinum-denis/rafflebot/src/containers/App.test.tsx']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/infinum-denis/rafflebot/src/App.test.tsx',
  dest: '/Users/infinum-denis/rafflebot/src/containers/App.test.tsx' }
```

Any ideas what's the issue here? The directory is created, but I'm not sure if all was setup correctly due to the above error.

**Comment by DarkoKukovec** [comment]
I can't reproduce the issue :/

Can you please answer the following questions:
* Does any of the mentioned files exist?
* If not, do you have the file if you run `npx create-react-app <name>`?
* What node version do you have?
* What npm version do you have?
* Do you have yarn, and if so, which version?

**Comment by dingo-d** [comment]
`App.test.tsx` exists in `src/containers/` folder (empty file), there is no `App.test.tsx` in `src/` folder (when created using `npx @infinumjs/cra-starter -s rafflebot`).

When I created the `npx create-react-app rafflebot2` there are no `tsx` files at all, and no `src/containers` folder as well.

Node version: 10.11.0
npm version: 6.4.1
yarn version: 1.10.1

**Comment by DarkoKukovec** [comment]
Sorry, I meant `npx create-react-app <name> --typescript`...
I'm assuming this issue is consistent?

**Comment by dingo-d** [comment]
Works fine when I do `npx create-react-app rafflebot --typescript`

**Comment by DarkoKukovec** [comment]
@mamihelj09 seemed to track this down. @dingo-d do you maybe have the original CRA installed globally?

**Comment by dingo-d** [comment]
Seems like it, I just successfully ran `npx create-react-app rafflebot --typescript` and it failed with `npx @infinumjs/cra-starter -s rafflebot`

<details>
<summary>Error message</summary>
```bash
npx: installed 8 in 2.445s
{ Error: Command failed: git add . && git commit -m "Project setup"
husky > pre-commit (node v11.12.0)

> rafflebot@0.1.0 lint /Users/infinum-denis/Projects/Personal/rafflebot/rafflebot
> prettier --check **/*.{ts,tsx} !dist/** && eslint **/*.{ts,tsx}

Checking formatting...
All matched files use Prettier code style!

Oops! Something went wrong! :(

ESLint: 5.16.0.
No files matching the pattern "node_modules/microevent.ts" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rafflebot@0.1.0 lint: `prettier --check **/*.{ts,tsx} !dist/** && eslint **/*.{ts,tsx}`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the rafflebot@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/infinum-denis/.npm/_logs/2019-05-13T10_43_41_344Z-debug.log
husky > pre-commit hook failed (add --no-verify to bypass)

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:988:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'git add . && git commit -m "Project setup"' }
```
</details>
